# Change these first
owner: gani0325 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: alpaca
    url: https://alpaca-gt.tistory.com/

status-website:
  name: Upptime for alpaca.com
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: upptime.alpaca.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
